name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test
    strategy:
      matrix:
        scala: [ 2.13.x, 3.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '11'
          java-package: jdk

      - name: Cache SBT
        uses: coursier/cache-action@v6
        with:
          extraKey: v1

      - name: Lint
        run: sbt --client "++${{ matrix.scala }} scalafmtCheckAll"

      - name: Compile
        run: sbt --client "++${{ matrix.scala }} Test/compile"

      - name: Test
        run: sbt --client "++${{ matrix.scala }} test"
